language: r
sudo: required
cache: packages
services:
  - docker
r_packages:
  - covr
before_script:
  - docker pull bfirsh/reticulate-splines
  - sudo pip install -U setuptools
  - sudo pip install -U docker
after_success:
  - Rscript -e 'covr::codecov()'
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - python-numpy
      - python-requests
